name: ncms
type: php
docroot: ""
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
use_dns_when_possible: true
host_db_port: "33060"
timezone: America/Bahia
composer_version: "2"
web_environment: []
corepack_enable: false
